"use client";

import { useState } from "react";
import { useFormStatus } from "react-dom";
import { toast } from "sonner";
import { Loader2, Sparkles, Wand2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { EvidenceFilePicker } from "@/components/evidence-file-picker";
import { createBug } from "../actions";
import {
  BUG_PRIORITIES,
  BUG_SEVERITIES,
  type BugPriority,
  type BugSeverity,
} from "@/types/database";

interface GeneratedFields {
  title: string;
  description: string;
  priority: BugPriority;
  severity: BugSeverity;
  steps_to_reproduce: string;
  actual_result: string;
  expected_result: string;
}

const EMPTY_FIELDS: GeneratedFields = {
  title: "",
  description: "",
  priority: "Medium",
  severity: "Minor",
  steps_to_reproduce: "",
  actual_result: "",
  expected_result: "",
};

function SubmitButton({ disabled }: { disabled?: boolean }) {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" size="lg" disabled={pending || disabled}>
      {pending ? <Loader2 className="size-4 animate-spin" /> : null}
      {pending ? "Saving..." : "Save Bug Report"}
    </Button>
  );
}

export function NewBugForm() {
  const [rawText, setRawText] = useState("");
  const [generating, setGenerating] = useState(false);
  const [aiGenerated, setAiGenerated] = useState(false);
  const [fields, setFields] = useState<GeneratedFields>(EMPTY_FIELDS);

  async function handleGenerate() {
    if (!rawText.trim()) {
      toast.error("Describe the bug before generating a report.");
      return;
    }
    setGenerating(true);
    try {
      const res = await fetch("/api/ai/generate-bug-report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ rawText }),
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "Failed to generate the bug report.");
      }
      setFields(data.report);
      setAiGenerated(true);
      toast.success("Bug report generated. Review and edit before saving.");
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Failed to generate the bug report.",
      );
    } finally {
      setGenerating(false);
    }
  }

  const canSubmit = fields.title.trim() !== "" && fields.description.trim() !== "";

  return (
    <div className="space-y-10">
      <div className="space-y-3 rounded-lg border p-4">
        <div className="flex items-center gap-2 text-sm font-medium">
          <Wand2 className="size-4" strokeWidth={1.5} />
          AI Assist
          {aiGenerated ? (
            <span className="text-xs font-normal text-muted-foreground">
              — Generated by AI, please review before saving
            </span>
          ) : null}
        </div>
        <p className="text-sm text-muted-foreground">
          Describe the bug in any language. It will be translated into a
          structured English report.
        </p>
        <Textarea
          id="raw-text"
          rows={5}
          placeholder="e.g., Clicking the checkout button on the cart page causes the application to freeze, requiring a manual refresh."
          value={rawText}
          onChange={(e) => setRawText(e.target.value)}
        />
        <Button type="button" variant="outline" onClick={handleGenerate} disabled={generating}>
          {generating ? (
            <Loader2 className="size-4 animate-spin" />
          ) : (
            <Sparkles className="size-4" />
          )}
          {generating ? "Generating..." : "Generate with AI"}
        </Button>
      </div>

      <form action={createBug} className="space-y-10">
        <input type="hidden" name="ai_generated" value={String(aiGenerated)} />
        <input type="hidden" name="original_report" value={rawText} />

        <div className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="title">Title</Label>
            <Input
              id="title"
              name="title"
              required
              value={fields.title}
              onChange={(e) => setFields((f) => ({ ...f, title: e.target.value }))}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              name="description"
              rows={3}
              required
              value={fields.description}
              onChange={(e) =>
                setFields((f) => ({ ...f, description: e.target.value }))
              }
            />
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="priority">Priority</Label>
              <Select
                value={fields.priority}
                onValueChange={(v) =>
                  setFields((f) => ({ ...f, priority: v as BugPriority }))
                }
              >
                <SelectTrigger id="priority" className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {BUG_PRIORITIES.map((p) => (
                    <SelectItem key={p} value={p}>
                      {p}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <input type="hidden" name="priority" value={fields.priority} />
            </div>

            <div className="space-y-2">
              <Label htmlFor="severity">Severity</Label>
              <Select
                value={fields.severity}
                onValueChange={(v) =>
                  setFields((f) => ({ ...f, severity: v as BugSeverity }))
                }
              >
                <SelectTrigger id="severity" className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {BUG_SEVERITIES.map((s) => (
                    <SelectItem key={s} value={s}>
                      {s}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <input type="hidden" name="severity" value={fields.severity} />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="steps">Steps to Reproduce</Label>
            <Textarea
              id="steps"
              name="steps_to_reproduce"
              rows={4}
              value={fields.steps_to_reproduce}
              onChange={(e) =>
                setFields((f) => ({ ...f, steps_to_reproduce: e.target.value }))
              }
            />
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label htmlFor="actual">Actual Result</Label>
              <Textarea
                id="actual"
                name="actual_result"
                rows={3}
                value={fields.actual_result}
                onChange={(e) =>
                  setFields((f) => ({ ...f, actual_result: e.target.value }))
                }
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="expected">Expected Result</Label>
              <Textarea
                id="expected"
                name="expected_result"
                rows={3}
                value={fields.expected_result}
                onChange={(e) =>
                  setFields((f) => ({ ...f, expected_result: e.target.value }))
                }
              />
            </div>
          </div>
        </div>

        <div className="space-y-3 border-t pt-6">
          <Label>Evidence</Label>
          <EvidenceFilePicker />
        </div>

        <SubmitButton disabled={!canSubmit} />
      </form>
    </div>
  );
}
